development:
  paypal:
    login: khw212_1338861554_biz_api1.gmail.com
    password: 1338861588
    signature: A6aKY1rdzYKveggqS0dCSlcOacTKABO0H79hKoBZiQlZDjaOoXvAOJFX
  authorizenet:
    login: 6H6WXRje43jF
    password: 9Gt238h7vWkS2Ckh
  freshbook:
    login: vtn-billing.freshbooks.com
    password: f26f576d8a60a60324e139b575a9a8fa

production:
  paypal:
    login: rjohnston_api1.colosses.com
    password: BAT9ZE4X6EAXU46Q
    signature: ABwmBAIEJPBtRUnk9k-iMfCgx5nrAMrnY9L1hhyI4NzMx5OtLtkrsOmr
  authorizenet:
    login: 29U2GgeyC7
    password: 4A62xU5m63mQ7vTH
  freshbook:
    login: vtn-billing.freshbooks.com
    password: f26f576d8a60a60324e139b575a9a8fa

staging:
  paypal:
    login: khw212_1338861554_biz_api1.gmail.com
    password: 1338861588
    signature: A6aKY1rdzYKveggqS0dCSlcOacTKABO0H79hKoBZiQlZDjaOoXvAOJFX
  authorizenet:
    login: 4A4b8SXUt6M
    password: 4wugYeKPq29365bk

test:
  paypal:
    login: khw212_1338861554_biz_api1.gmail.com
    password: 1338861588
    signature: A6aKY1rdzYKveggqS0dCSlcOacTKABO0H79hKoBZiQlZDjaOoXvAOJFX
  authorizenet:
    login: 4A4b8SXUt6M
    password: 4wugYeKPq29365bk

sandbox:
  paypal:
    login: khw212_1338861554_biz_api1.gmail.com
    password: 1338861588
    signature: A6aKY1rdzYKveggqS0dCSlcOacTKABO0H79hKoBZiQlZDjaOoXvAOJFX
  authorizenet:
    login: 4B8uttN6EK
    password: 3R5455NyA2vz2nCz

